### ISSUE TITLE
Ruby 2.3 support?

### ISSUE THREAD

**Issue by thbar** [twalpole/apparition#1]
Thanks for this new project, which I'm eager to try in replacement of `poltergeist`!

I tried installing it on a legacy codebase, still on Ruby 2.3, and I wondered why it required 2.4+? Are there specific features of Ruby that you really need, or is it in anticipation of the fact that 2.3 is EOL in 2 months?

(I can always fork in the mean time, but since `apparition` is likely to change a bit these days, it would be easier to just target your repo directly!).

Thanks for your feedback!

**Comment by twalpole** [comment]
I went 2.4+ because of the EOL of 2.3 coming up shortly, and there probably are 2.4+ methods in use (match? at least). Does your app not run on 2.4? I don't remember any breaking changes from 2.3 to 2.4

**Comment by thbar** [comment]
Ok so this is what I assumed :-) Do not bother at this point, especially given that the EOL is coming so soon. I was more curious than anything.

That said yes - the app I'm porting is not yet working (test suite) on 2.4 & I still have a few failures to fix!

I'll close for now - thanks for your input!

**Comment by twalpole** [comment]
@thbar Just curious -- what issues have you run into moving form 2.3 to 2.4?? Would be good to know for others as the EOL approaches

**Comment by twalpole** [comment]
@thbar Also - try the ruby_2.3 branch in this repo for a version that should work with ruby 2.3

**Comment by thbar** [comment]
@twalpole FYI, all the failures in the app I was referring to are caused by this regression in how `BigDecimal("")` works https://github.com/ruby/bigdecimal/issues/51.

This can be fixed by adding `big_decimal` as a gem, or changed in the code (but Ruby 2.4 behaviour, even in latest patch releases, is still in regression compared to 2.3).

**Comment by thbar** [comment]
@twalpole the `ruby_2.3` branch worked perfectly. Many thanks!

**Comment by twalpole** [comment]
@thbar Good to hear -- I pulled it into main.  Have you run into any other issues using `apparition`??

**Comment by thbar** [comment]
@twalpole Thanks for integrating this!

Yes, I ran into another issue (although a very specific one).

I will open another issue for that!
