### ISSUE TITLE
fill_in slower?

### ISSUE THREAD

**Issue by will** [twalpole/apparition#17]
Is there a way to get fill_in to type more slowly? I have a form that uses some javascript form Stripe to verify credit card checksums or whatever it does and that seems to be slow enough that numbers are skipped when filling in that field.

``` ruby
fill_in "cc-number", with: "4242424242424242"
```
![image](https://user-images.githubusercontent.com/1973/59311734-71c49080-8c5f-11e9-9fb7-d01d14a3ce2a.png)
Notice the repeated `4`s when the literal is all alternating. 

When running in not-headless, it doesn't fail, I guess because actually rendering the input is slow enough, whereas in headless it can go faster. 

In the meantime I've worked around this by making a helper that cheats by directly setting the value property, but I'm wondering if there is another way that would be "better"?

``` ruby
  def cheat_fill_in(id, opts)
    page.driver.evaluate_script "document.getElementById('#{id}').value = '#{opts[:with]}'"
  end
```

**Comment by twalpole** [comment]
@will Yes - Apparition supports a `delay` option when filling in text fields. You can do 

    fill_in "cc-number", with: "4242424242424242", fill_options: { delay: 0.1 }

to wait 0.1 seconds between each key press.  If you have already found the element then you could also do

    element.set("4242424242424242", delay: 0.1)

**Comment by will** [comment]
Thank you!

**Comment by sfcgeorge** [comment]
Hah, I had exactly this issue down to the 4242424242424242 string. Thanks!
