### ISSUE TITLE
CircleCi fails to finish

### ISSUE THREAD

**Issue by DangerDawson** [twalpole/apparition#28]
The following commit is preventing for CircleCi from completing:

https://github.com/twalpole/apparition/commit/9043f020b87ea5ab21e336889a302d4103c697a0

I am guessing it is something to do with the way it is writing out to stderr / stdout

**Comment by twalpole** [comment]
@DangerDawson What Ruby are you running with, etc?

**Comment by twalpole** [comment]
As can be seen at https://travis-ci.org/twalpole/apparition/jobs/572503750 - the tests finish when run on travis (with a couple of errors) so whatever is causing this on your run is something specific to your running of it, so a lot more info is necessary to diagnose.

**Comment by twalpole** [comment]
Closing due to lack of response

**Comment by DangerDawson** [comment]
Sorry for the slow reply, I was away on vacation and only just returned.

I was running it with ruby 2.6.3 and also using  the parallel_test gem: https://github.com/grosser/parallel_tests

I will spend some time this week diagnosing what is actually happening, but it seems not to happen with the previous version, and specifically with the commit I mentioned above reverted

**Comment by ronanmcnulty** [comment]
I'm having the same issue with ruby 2.6.3 and parallel_test gem
