### ISSUE TITLE
Unexpected caching issues conflicting with CORB

### ISSUE THREAD

**Issue by geoffharcourt** [twalpole/apparition#29]
Hi,

I'm trying to pull together enough telemetry to help explain what's going on, but we have a very specific error we see with Apparition that we don't see in our other use of Chrome or with Selenium + Chromedriver.

The issue happens when certain system specs try to make GET API requests. The server performs the render/response and returns data, but Chrome/Apparition tries to return the data from cache. The result (presumably returned from cache) is missing the `Content-Type` header that's normally present in the response, and Chrome 73's CORB blocking returns an empty response instead of the JSON our API sent back. I am also unclear as to how there's anything in the cache at all at this point.

Here's an example of the console log response:

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://127.0.0.1:51183/api/v1/texts?locale=en with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

The request for the network tab for this request is 200 OK with these headers:

```
Provisional headers are shown
Accept: application/json, text/plain, */*
Referer: http://127.0.0.1:51183/assignments/in-progress
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36
X-CSRF-Token: [object Object]
X-Requested-With: XMLHttpRequest
```

If we do a hard-reload in the browser re-execute this request, it always succeeds on the second attempt. We're at a loss for what's pre-populating the cache with the result of this API request since the session runs in incognito mode, and shouldn't have any cache to start.

When we hard-reload, we get the same request headers (except without the Provisional Headers warning, as the request succeeds), and the response comes back with the data we expect:

```
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
ETag: W/"d37bdcc5c109f4a02f3fd13d24d30cce"
Referrer-Policy: strict-origin-when-cross-origin
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 1774dc8b-65c0-498d-a094-6a3b0ccd9ebf
X-Runtime: 0.328993
X-XSS-Protection: 1; mode=block
```

Do you have any ideas as to what might be wrong here that we can fix? We can't produce this in other drivers, but we very much want to transition over to Apparition.

**Comment by geoffharcourt** [comment]
One further note: the specs that have these CORB problems pass with Cuprite, so I don't think this is an issue with our app or Chrome.

**Comment by twalpole** [comment]
Any chance of a reproducible test case?

**Comment by geoffharcourt** [comment]
Yeah, I'm sorry this isn't more specific. I'm trying to build a small enough application to produce the problem.

**Comment by twalpole** [comment]
Something like https://gist.github.com/twalpole/6711ad9aedf4449d5edb01890726e81b is the simplest, although it may be too simple for your situation

**Comment by geoffharcourt** [comment]
Still working on a streamlined test case app, but adding

```
  browser_options: {
    "disable-web-security" => nil,
  },
```

to my Apparition options makes the tests work successfully (but obviously that's not a great solution).

**Comment by baffers** [comment]
+1...  I've found using `page.refresh` after loading a page that will fire async JS  will prevent the `Provisional headers` problem.. Obviously that solution doesn't scale. I'll give the `disable-web-security` a shot.

**Comment by geoffharcourt** [comment]
I haven't been able to get a small app together yet, but every time I've used a binding to halt the test and have reloaded the page once these issues resolve themselves for the rest of that example.

**Comment by twalpole** [comment]
Any update on a reproducible test case for this?

**Comment by geoffharcourt** [comment]
I tried adapting the script you provided but I can't reproduce the issue in it. I tried injecting all the headers from our report into the output to see if I could get a `jQuery.get` call to return the issue (so setting the same Cache-Control, etc) without success.

**Comment by geoffharcourt** [comment]
Update: I can't reproduce this by pointing the test script you suggested at our production app at a page that fails in test. I'm looking into whether this somehow has anything to do with requests that are on a non-standard HTTP port number in hopes that will be reproducible in a publicly-sharable case.

**Comment by geoffharcourt** [comment]
Something is different in newer versions of Chrome, and this problem solved itself even on older versions of our app from the time of the initial issue report. Thanks for your advice about things to try and sorry for the noise!

**Comment by geoffharcourt** [comment]
I was wrong, it's just itermittent. Holding off on reopening until I can generate this in a publicly-sharable app.

**Comment by geoffharcourt** [comment]
An update here: this appears to also be a problem in Cuprite, but Cuprite has dealt with it by setting `disable-web-security` out of the box: https://github.com/machinio/cuprite/issues/71

This makes me think this issue might be related to CDP and not specific to these drivers.

**Comment by twalpole** [comment]
Hmmm -- disabling web security doesn't really seem like a good idea

**Comment by geoffharcourt** [comment]
Agreed. I just wanted to add that here since earlier in the issue I had said it wasn't a problem with Cuprite (thinking it was a unique issue in Apparition).

**Comment by MinasMazar** [comment]
I experienced the same issue. Don't know if it can help the investigation, but putting a `before { Capybara.current_session.driver.headers = {} }` in the spec was enough to make it green.
