### ISSUE TITLE
Capybara `fill_in` does not trigger `blur` event

### ISSUE THREAD

**Issue by henrik** [twalpole/apparition#33]
This caused some specs to stop working after moving from Poltergeist to Apparition.

I'm not sure if it's sensible or not for  `fill_in` to trigger the `blur` event, but if this lib aims to be drop-in compatible with Poltergeist, maybe it's worth considering.

I fixed it by adding and using this method:

```
def fill_in_then_blur(field_name, value)
  fill_in field_name, with: value

  # Trigger a JS blur event.
  find("body").click
end
```

**Comment by twalpole** [comment]
Apparition isn't trying to be a drop-in replacement for Poltergeist, it's trying to be a driver that passes the same tests as Selenium does, but also provides the extra features Poltergeist did (network traffic, whitelists/blacklists, etc)

**Comment by henrik** [comment]
Ah, alright. I wasn't sure how to interpet

> It started as a fork of Poltergeist and attempts to maintain as much compatibility with the Poltergeist API as possible.

Good to know, then – won't report any further differences to Poltergeist unless they feel like bugs :)

**Comment by henrik** [comment]
We had to change this – not sure why, perhaps a new version of Chrome? We now do:

``` ruby
  def fill_in_then_blur(locator, with:)
    fill_in(locator, with:)
    find_field(locator).native.send_keys :tab # Tab away from the element to trigger a blur event.
  end
```
