### ISSUE TITLE
cuprite & apparition

### ISSUE THREAD

**Issue by ryan-plated** [twalpole/apparition#4]
https://github.com/machinio/cuprite

you and @machinio should talk

**Comment by twalpole** [comment]
We talked many times when he was working on cuprite (I am a committer on the Poltergeist project too) - I had started this project quite a while ago when CDP wasn't stable enough to make this work properly., but  over time CDP has become usable and route started working on his own version of this.  I don't see an issue with 2 different drivers co-existing currently.

**Comment by rmacklin** [comment]
@twalpole:
> I don't see an issue with 2 different drivers co-existing currently.

I agree with this. That said, as someone considering migrating away from selenium/chromedriver to one of these projects, I'm interested in learning what the main differences are between the two.

I'm curious if you're familiar enough with cuprite to speak on its differences with apparition (pros/cons of each). I think even a brief description would be helpful for the community.
