### ISSUE TITLE
Capybara's "visit" hangs on Amazon Linux

### ISSUE THREAD

**Issue by alexchumak** [twalpole/apparition#46]
Here's a snippet of what I get running a rake task that scrapes a website. It hangs after the warning and the rest of the output is after I hit control-C.. It hangs on the first visit request.

Works great locally on my macbook.

Amazon Linux setup info:
- Linux 4.4.19-29.55.amzn1.x86_64
- google-chrome version 80.0.3987.163
- I dont think it's needed but I also have ChromeDriver 2.37.544315 installed.

Where did i go wrong?

```
../ruby/2.3.0/gems/apparition-0.1.0/lib/capybara/apparition/dev_tools_protocol/remote_object.rb:47: warning: redefining `object_id' may cause serious problems
^Crake aborted!
Interrupt:
../ruby/2.3.0/gems/apparition-0.1.0/lib/capybara/apparition/driver/launcher.rb:90:in `pop'
../2.3.0/gems/apparition-0.1.0/lib/capybara/apparition/driver/launcher.rb:90:in `block in ws_url'
../ruby/2.3.0/gems/apparition-0.1.0/lib/capybara/apparition/driver/launcher.rb:89:in `loop'
../ruby/2.3.0/gems/apparition-0.1.0/lib/capybara/apparition/driver/launcher.rb:89:in `ws_url'
../ruby/2.3.0/gems/apparition-0.1.0/lib/capybara/apparition/driver.rb:69:in `client'
../2.3.0/gems/apparition-0.1.0/lib/capybara/apparition/driver.rb:48:in `browser'
../ruby/2.3.0/gems/apparition-0.1.0/lib/capybara/apparition/driver.rb:91:in `visit'
../ruby/2.3.0/gems/capybara-3.15.1/lib/capybara/session.rb:277:in `visit'
../ruby/2.3.0/gems/capybara-3.15.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
```

Let me know if I missed anything.

Thank you in advance.

**Comment by twalpole** [comment]
Apparition 0.1.0 is ancient -- please use either the latest release, or better the master branch.

**Comment by alexchumak** [comment]
Only a year old! :)

Hmmm... Anything newer depends on ruby 2.4 and we're stuck with 2.3.7 for the foreseeable future. Not great.

Thank you for the response.
