### ISSUE TITLE
Errno::ECONNREFUSED:Connection refused

### ISSUE THREAD

**Issue by smith558** [twalpole/apparition#54]
Getting exception `Errno::ECONNREFUSED:Connection refused - connect(2) for "127.0.0.1" port 55031` when running RSPEC examples with Capybara using Apparition driver. Selenium works just fine. Port changes with each run, fails the same way.

Ubuntu 18.04 WSL 1
ChromeDriver 81.0.4044.138

**Comment by twalpole** [comment]
Sounds like your chromedriver or chrome is failing to run

**Comment by smith558** [comment]
@twalpole But Selenium-webdriver on the same configuration works just fine (chrome, headless)
Not I got to have chromedriver and Chrome on Windows on PATH, 

I am using WSL and trying to run headless.

My configuration:
```
Capybara.register_driver :apparition do |app|
  Capybara::Apparition::Driver.new(app,
    url_blacklist: ['fonts.googleapis.com'],
    js_errors: false,
    browser_logger: nil,
    headless: true,
    browser_options: [:disable_gpu, :no_sandbox, disable_features: 'VizDisplayCompositor'])
end
Capybara.javascript_driver = :apparition
```

console output when fails:
```
All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 36689

Admin::Edesk::BoxesPackages
Capybara starting Puma...
* Version 3.12.4 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:59890
  is possible to generate package for nases (FAILED - 1)

Failures:

  1) Private RSPEC tests
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit site_path

          Errno::ECONNREFUSED:
            Connection refused - connect(2) for "127.0.0.1" port 59896
          # ./spec/features/private:in `block (2 levels) in <top (required)>'
          # ./spec/support/database_shared_connection.rb:29:in `block (2 levels) in <top (required)>'
```

**Comment by twalpole** [comment]
I don’t have a windows machine currently so apparition may not know how to find Chrome on your configuration. PRs welcome

**Comment by smith558** [comment]
Moved to an alternative.
