### ISSUE TITLE
Logger without public puts method crashes

### ISSUE THREAD

**Issue by dorner** [twalpole/apparition#57]
The default Logger class in Ruby does not have a public puts method:
https://ruby-doc.org/stdlib-2.6.3/libdoc/logger/rdoc/Logger.html

When trying to set the browser logger to something like `Logger.new(nil)` to essentially prevent all output, this crashes since it doesn't have a `puts` statement.

Is there a reason we're using `puts` instead of `debug`, `info`, `write`, etc.?

**Comment by twalpole** [comment]
Yes - because this gem was designed to ease the transition off Poltergeist and that's what the Poltergeist logger option provided.  If you'd like to provide a PR that enhances that it would be considered.
