### ISSUE TITLE
Does not submit empty form parameters

### ISSUE THREAD

**Issue by henrik** [twalpole/apparition#63]
Hi!

I've got this GET form, submitted via Turbolinks: https://auctionet.com/search/start_for_apps

I checked in Chrome, an iOS web view and Firefox – they all include empty params in the URL if I search for "foo" and leave the other fields at their default values. E.g. "…query=foo&category_id=&…".

But Apparition does not. The path will be just "/search?utf8=%E2%9C%93&is=&q=foo", without those extra params.

This recently meant a bug slipped through into production that would have been caught in tests if they had included these empty params, too.

I don't know what browser specs say about this, but I thought I'd raise it as a potential issue, anyway :)

**Comment by twalpole** [comment]
Not really sure how apparition would be affecting this -- the browser is what serializes the form and submits it.
