### ISSUE TITLE
Google Chrome quit unexpectedly.

### ISSUE THREAD

**Issue by skyeagle** [twalpole/apparition#9]
Thanks for the fantastic gem!

Everything looks fine except one thing. Chome periodically crashes at the end of the process of running specs and Mac creates a crash report.

The issue does exist for non-headless mode on Mac. I tried to debug it and seems like Chrome's process gets killed before a [proc of process killer](https://github.com/twalpole/apparition/blob/bde196d734276578fe5394736d0c6f467331f1c7/lib/capybara/apparition/driver/launcher.rb#L12) gets executed.

A simple repro is to run this spec in non-headless mode (I've changed it to false in spec/spec_helper.rb)
```
rspec spec/capybara-webkit/driver_rendering_spec.rb:50
```

Any ideas of how it could be fixed? I'd love to help and provide any needed info.

Thanks in advance!

**Comment by twalpole** [comment]
Unfortunately I can't replicate this - With Chrome 73.0.3683.103 on macOS 10.14.4 .  Is that the same as you're using?  Are you using the current master branch?

**Comment by twalpole** [comment]
Ok - It replicates now - not really sure what we can do about it - the process just isn't ending when told to sometime - even if I increase KILL_TIMEOUT to a much larger value Chrome appears to ignore the TERM signal sometimes and then eventually gets force killed - I'm open to any ideas

**Comment by twalpole** [comment]
@skyeagle Ok - fixed it - It was sending the wrong signal to Chrome to fully shut it down.  Please give the master branch a try now.

**Comment by skyeagle** [comment]
@twalpole it worked, awesome! blazing fast fix, thank you so much for such exciting work!
